// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2bdGmsQqwd0FwPh778bYhw0Y4yyK5-zc',
    appId: '1:354988248270:web:02f9a679ffbb00e461549f',
    messagingSenderId: '354988248270',
    projectId: 'projectpab-bfd21',
    authDomain: 'projectpab-bfd21.firebaseapp.com',
    storageBucket: 'projectpab-bfd21.appspot.com',
    measurementId: 'G-LNW9LC5BDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb4MPVAPSt7j2X6aIxN62bUEHCcbigQjo',
    appId: '1:354988248270:android:39a0aa5130a8ff2561549f',
    messagingSenderId: '354988248270',
    projectId: 'projectpab-bfd21',
    storageBucket: 'projectpab-bfd21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvQTUDZxH2EbMIlTfpTdIXo8o3Qvx2sCI',
    appId: '1:354988248270:ios:92a9f29f97a20b3c61549f',
    messagingSenderId: '354988248270',
    projectId: 'projectpab-bfd21',
    storageBucket: 'projectpab-bfd21.appspot.com',
    iosBundleId: 'com.example.infoloker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvQTUDZxH2EbMIlTfpTdIXo8o3Qvx2sCI',
    appId: '1:354988248270:ios:92a9f29f97a20b3c61549f',
    messagingSenderId: '354988248270',
    projectId: 'projectpab-bfd21',
    storageBucket: 'projectpab-bfd21.appspot.com',
    iosBundleId: 'com.example.infoloker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2bdGmsQqwd0FwPh778bYhw0Y4yyK5-zc',
    appId: '1:354988248270:web:730f63399e389a5761549f',
    messagingSenderId: '354988248270',
    projectId: 'projectpab-bfd21',
    authDomain: 'projectpab-bfd21.firebaseapp.com',
    storageBucket: 'projectpab-bfd21.appspot.com',
    measurementId: 'G-TGKHHL33VT',
  );

}