// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB78DDMxSR7RZzKw7tqBPXCoiZdTii5NPk',
    appId: '1:772442408374:web:67f4848ed8c1288436ed17',
    messagingSenderId: '772442408374',
    projectId: 'utspaboctarian',
    authDomain: 'utspaboctarian.firebaseapp.com',
    databaseURL: 'https://utspaboctarian-default-rtdb.firebaseio.com',
    storageBucket: 'utspaboctarian.appspot.com',
    measurementId: 'G-P6EDSQBPKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQb1rujzkYcWyYyy_DMl_N7LXcJYox1Cc',
    appId: '1:772442408374:android:731efa1d21c78b5936ed17',
    messagingSenderId: '772442408374',
    projectId: 'utspaboctarian',
    databaseURL: 'https://utspaboctarian-default-rtdb.firebaseio.com',
    storageBucket: 'utspaboctarian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArMQg1gnUjSI1jqgHMxSTuBvhmLhuMa4s',
    appId: '1:772442408374:ios:88452d1599e22d1a36ed17',
    messagingSenderId: '772442408374',
    projectId: 'utspaboctarian',
    databaseURL: 'https://utspaboctarian-default-rtdb.firebaseio.com',
    storageBucket: 'utspaboctarian.appspot.com',
    iosBundleId: 'com.example.utspaboctarian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArMQg1gnUjSI1jqgHMxSTuBvhmLhuMa4s',
    appId: '1:772442408374:ios:88452d1599e22d1a36ed17',
    messagingSenderId: '772442408374',
    projectId: 'utspaboctarian',
    databaseURL: 'https://utspaboctarian-default-rtdb.firebaseio.com',
    storageBucket: 'utspaboctarian.appspot.com',
    iosBundleId: 'com.example.utspaboctarian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB78DDMxSR7RZzKw7tqBPXCoiZdTii5NPk',
    appId: '1:772442408374:web:85039d5f8069a82a36ed17',
    messagingSenderId: '772442408374',
    projectId: 'utspaboctarian',
    authDomain: 'utspaboctarian.firebaseapp.com',
    databaseURL: 'https://utspaboctarian-default-rtdb.firebaseio.com',
    storageBucket: 'utspaboctarian.appspot.com',
    measurementId: 'G-TM54V7P16F',
  );

}