// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX57ikFVO4-NcPP8IcNQi1WtBdNW4Yq88',
    appId: '1:447348734117:web:4aed13ee9b7ff65dd2354c',
    messagingSenderId: '447348734117',
    projectId: 'notes-e2638',
    authDomain: 'notes-e2638.firebaseapp.com',
    storageBucket: 'notes-e2638.appspot.com',
    measurementId: 'G-LCP5YW0X6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7u-YHzlWJnYq_yYmTHxCfwr_aRT17d1k',
    appId: '1:447348734117:android:8a6ff249441d2c3dd2354c',
    messagingSenderId: '447348734117',
    projectId: 'notes-e2638',
    storageBucket: 'notes-e2638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZbBfdhjglbG2fCmtPIOqTAw5HT6uSIPE',
    appId: '1:447348734117:ios:3323059ec5f3fe78d2354c',
    messagingSenderId: '447348734117',
    projectId: 'notes-e2638',
    storageBucket: 'notes-e2638.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZbBfdhjglbG2fCmtPIOqTAw5HT6uSIPE',
    appId: '1:447348734117:ios:3323059ec5f3fe78d2354c',
    messagingSenderId: '447348734117',
    projectId: 'notes-e2638',
    storageBucket: 'notes-e2638.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX57ikFVO4-NcPP8IcNQi1WtBdNW4Yq88',
    appId: '1:447348734117:web:d1bdf4cc319414bed2354c',
    messagingSenderId: '447348734117',
    projectId: 'notes-e2638',
    authDomain: 'notes-e2638.firebaseapp.com',
    storageBucket: 'notes-e2638.appspot.com',
    measurementId: 'G-QPF0G5X8S3',
  );

}