// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy5dgRCgmDo0-D0jWuzC9xc1Uy-S5MdBg',
    appId: '1:915192720719:web:5489491d7b4ff9fc7c293a',
    messagingSenderId: '915192720719',
    projectId: 'lokerproject-ad7e5',
    authDomain: 'lokerproject-ad7e5.firebaseapp.com',
    storageBucket: 'lokerproject-ad7e5.appspot.com',
    measurementId: 'G-09LJ0HPKY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMnbxuCee7h3D7bUP9uPGnDd891FX7qhc',
    appId: '1:915192720719:android:e49344cd14a218ac7c293a',
    messagingSenderId: '915192720719',
    projectId: 'lokerproject-ad7e5',
    storageBucket: 'lokerproject-ad7e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGvL-PyYoVJhcW8SKCNZeI5xNqTnlHMEQ',
    appId: '1:915192720719:ios:324ad8d401934eab7c293a',
    messagingSenderId: '915192720719',
    projectId: 'lokerproject-ad7e5',
    storageBucket: 'lokerproject-ad7e5.appspot.com',
    iosBundleId: 'com.example.infoloker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGvL-PyYoVJhcW8SKCNZeI5xNqTnlHMEQ',
    appId: '1:915192720719:ios:324ad8d401934eab7c293a',
    messagingSenderId: '915192720719',
    projectId: 'lokerproject-ad7e5',
    storageBucket: 'lokerproject-ad7e5.appspot.com',
    iosBundleId: 'com.example.infoloker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy5dgRCgmDo0-D0jWuzC9xc1Uy-S5MdBg',
    appId: '1:915192720719:web:56a926fd115da7ee7c293a',
    messagingSenderId: '915192720719',
    projectId: 'lokerproject-ad7e5',
    authDomain: 'lokerproject-ad7e5.firebaseapp.com',
    storageBucket: 'lokerproject-ad7e5.appspot.com',
    measurementId: 'G-SEC3B3SHWC',
  );

}